import type { Metadata } from "next";
import { Chela_One, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  weight:["200", "300","400","500","600","700","800"],
  subsets: ["latin"],
  
});
const chelaOne = Chela_One({
  variable: "--font-chela-one",
  weight:"400",
  subsets: ["latin"],
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${chelaOne.variable} h-full antialiased`}
    suppressHydrationWarning
    >


      <body className=" min-h-full bg-fondo text-letras font-(family-name:--font-inter) font-extrabold">
        <Script id="theme-init" strategy="beforeInteractive">
          {`
            if (localStorage.getItem("theme") === "dark") {
              document.documentElement.classList.add("dark");
            }
          `}
        </Script>
          {children}                      
      </body>
    </html>
  );
}
